server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client_id: 1068264261400-qv0d6bqncnbum707dv7n6nig3ucbvhot.apps.googleusercontent.com
            client_secret: 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
            scope:
              - email
              - profile
              -
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        #use_sql_comments: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # about swagger

  servlet.multipart.max-file-size: 5MB
  servlet.multipart.max-request-size: 5MB

jwt:
  key: vepvmiemvpmerimepoirmepoirmopervmepoirmvioemrvopiemrvoipemrvipoemrvoperopeovrpervoiemoimerpovmervpmio